Add link to supported authentication schemes
ansys/grantami-recordlists pull request #321
Opened 2024-09-20 13:26 UTC by ludovicsteinbach

https://github.com/ansys/pygranta/issues/109

Adds a link to the OpenAPI-Common documentation, to the section that presents supported auth methods in a formatted table.

2024-09-20 17:14 UTC, Andy-Grigg commented on doc/source/api/connection.rst
> +The OpenAPI-Common documentation lists supported `Authentication schemes <https://openapi.docs.pyansys.com/version/stable/index.html#authentication-schemes>`_.
As discussed, intersphinx doesn't seem to let you link to a specific heading if it doesn't have a label.

Separate question though, I'd prefer to have this more visible. The issue currently is that you have to get to the API docs just to understand what authentication schemes are available, which is really something that should be more clearly described 'higher up' in the docs.

Can this link come in on the User Guide, or Getting Started?

2024-09-24 09:13 UTC, ludovicsteinbach commented on doc/source/api/connection.rst
> +The OpenAPI-Common documentation lists supported `Authentication schemes <https://openapi.docs.pyansys.com/version/stable/index.html#authentication-schemes>`_.
I don't think the home/index page would be a good fit, given that it only includes the grid of links to other pages.

The Getting started page could work, there is a section `Verify your installation` which illustrates how to connect with autologon and then typically links to the `Examples` and `API reference` sections.

2024-09-25 16:24 UTC, Andy-Grigg requested changes

2024-09-25 16:24 UTC, Andy-Grigg commented on doc/source/conf.py
> +from packaging.version import parse as parse_version
I think I agree that this is a lot of additional complexity for minimal benefit. I suggest we always link to version/stable, and accept that in some possible scenarios people might end up looking at documentation for authentication schemes they can't use. We have no plans to radically change the authentication in a backwards-incompatible way though, so I think it is unlikely that this scenario will come to pass.

This extra code is just something else that could cause us problems in the future.

2024-09-26 13:11 UTC, Andy-Grigg approved these changes

2024-09-26 15:03 UTC, merged